export interface TerminalLine {
  type: "cmd" | "output" | "blank";
  text: string;
}

export const TERMINAL_LINES: TerminalLine[] = [
  { type: "cmd",    text: "docker compose run --rm forge" },
  { type: "output", text: "→ Fetching issue #42 from GitHub..." },
  { type: "output", text: "→ Starting Docker sandbox..." },
  { type: "output", text: "→ Cloning repository..." },
  { type: "blank",  text: "" },
  { type: "output", text: "[step 1] thought: I should explore the repo structure first." },
  { type: "output", text: "```bash" },
  { type: "output", text: "ls -F src" },
  { type: "output", text: "```" },
  { type: "output", text: "components/  utils/  App.tsx" },
  { type: "blank",  text: "" },
  { type: "output", text: "[step 2] thought: No utils dir yet, I'll create it." },
  { type: "output", text: "```bash" },
  { type: "output", text: "mkdir -p src/utils" },
  { type: "output", text: "```" },
  { type: "blank",  text: "" },
  { type: "output", text: "[step 3] thought: Writing the validation function." },
  { type: "output", text: "```bash" },
  { type: "output", text: "cat << 'EOF' > src/utils/validation.ts" },
  { type: "output", text: "export function isValidEmail(email: string): boolean {" },
  { type: "output", text: "  return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email);" },
  { type: "output", text: "}" },
  { type: "output", text: "EOF" },
  { type: "output", text: "```" },
  { type: "blank",  text: "" },
  { type: "output", text: "[step 4] thought: Done. Submitting patch." },
  { type: "output", text: "```bash" },
  { type: "output", text: "submit" },
  { type: "output", text: "```" },
  { type: "blank",  text: "" },
  { type: "output", text: "Run complete. Exit status: submitted" },
  { type: "output", text: "+export function isValidEmail(email: string): boolean {" },
  { type: "output", text: "+  return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email);" },
  { type: "output", text: "+}" },
  { type: "blank",  text: "" },
  { type: "output", text: "Pushing fix to branch..." },
  { type: "output", text: "Branch pushed: forge/issue-42" },
];
